# Survival Analysis 

In previous chapters, the outcomes we have been modeling have or have not occurred at a particular point in time following when the input variables were measured.  For example, in Chapter \@ref(lin-reg-ols) input variables were measured in the first three years of an education program and the outcome was measured at the end of the fourth and final year.  In many situations, the outcomes we are interested in are events that can occur at any time following when the input variables were measured, and can occur at different times for different individuals.  In medical studies, death can occur or the onset of a disease can be diagnosed at any time during the study period.  In employment contexts a promotion or attrition event can occur at various times through the year.  

An obvious and simple way to deal with this would be to simply agree to look at a specific point in time and measure whether or not the event had happened at that point, for example 'How many employees had left at the three year point?'.  Such an approach allows us to use standard generic regression models like those studied in previous chapters.  But these approaches have limitations.  

Firstly, we are only able to infer conclusions about the likelihood of the event having occurred as at the end of the period of study.  We cannot make inferences about the likelihood of the event throughout the period of study.  Being able to say that attrition is twice as likely for certain types of individuals at any time throughout the three years is more powerful than saying more twice as many of these individuals had left at the three year point.

Secondly, our sample size is constrained by the state of our data at the end of the period of study.  Therefore if we lose track of an individual after two years and six months, that observation needs to be dropped from our data set if we are focused only on the three year pont.  Wherever possible, loss of data is something a statistician will want to avoid as it effects the accuracy and statistical power of inferences. 

*Survival analysis* is a general term for the modeling of a time dependent binary outcome, usually involving understanding the comparative risk of that outcome between two or more different groups of interest.  There are two common components in an elementary survival analysis, as follows:

* A graphical representation of the future outcome risk of the different groups over time, using *Kaplan-Meier survival curves*.  This is usually an effective way to establish *prima facie* relevance of a certain input variable to the outcome, and is a very effective way of communicating the relevance to non-statisticians.
* A *Cox proportional hazards* regression model to establish statistical significance of input variables and to estimate the effect of each input variable on the comparitive risk of the outcome.  

Those seeking a more in depth treatment of survival analysis should consult texts on its use in medical/clinical contexts, and a recommended source is @collett. In this chapter we will use a walkthrough example to illustrate a typical use of survival analysis in a people analytics context.  We will use the `job_retention` dataset which can be downloaded [here](https://raw.githubusercontent.com/keithmcnulty/eampa/master/data/job_retention.csv).  

The `job_retention` dataset shows the results of a study of around 3,800 individuals employed in various fields of employment over a 1 year period.  At the beginning of the study, the individuals were asked to rate their sentiment towards their job.  These individuals were then followed up monthly for a year to determine if they were still working in the same job or had left for a substantially different job.  If an individual was not successfully followed up in a given month, they were no longer followed up for the remainder of the study period.   

The particular fields we are interested in in the `job_retention` data set are:

* `gender`:  The gender of the individual studied
* `field`: The field of employment that they worked in at the beginning of the study
* `level`:  The level of the position in their organization at the beginning of the study - `Low`, `Medium` or `High`.
* `sentiment`:   The sentiment score reported on a scale of 1 to 10, with 1 indicating extremely negative sentiment and 10 indicating extremely positive sentiment
* `left`: A binary variable indicating whether or not the individual had left their job as at the last follow-up
* `month`:  The month of the last follow up.  
