# Foreword by Alexis Fink {-}

Over the past decade or so, increases in compute power, emergence of friendly analytic tools and an
explosion of data have created a wonderful opportunity to bring more analytical rigor to nearly every
imaginable question. Not coincidentally, organizations are increasingly looking to apply all that data and
capability to what is typically their greatest area of expense and their greatest strategic differentiator---their people. For too long, many of the most critical decisions in an organization---people decisions---had been guided by gut instinct or borrowed 'best practices' and the democratization of people
analytics opened up enticing pathways to fix that. Suddenly, analysts who were originally interested in
data problems began to be interested in people problems, and HR professionals who had dedicated their
careers to solving people problems needed more sophisticated analysis and data storytelling to make
their cases and to refine their approaches for greater efficiency, effectiveness and impact.

Doing data work with people in organizations has complexities that some other types of data work
doesn’t. Often, the employee populations are relatively smaller than data sets used in other areas,
sometimes limiting the methods that can be used. Various regulatory requirements may dictate what
data can be gathered and used, and what types of evidence might be required for various programs or
people strategies. Human behavior and organizations are sufficiently complex that typically, multiple
factors work together in influencing an outcome. Effects can be subtle or meaningful only in
combination, or difficult to tease apart. While in many disciplines, prediction is the most important aim,
for most people analytics projects and practitioners, understanding *why* something is happening is
critical.

While the universe of analytical approaches is wonderful and vast, the best 'Swiss army knife' we have
in people analytics is regression. This volume is an accessible, targeted work aimed directly at
supporting professionals doing people analytics work. I’ve had the privilege of knowing and respecting
Keith McNulty for many years – he is the rare and marvelous individual who is deeply expert in the
mechanics of data and analytics, curious about and steeped in the opportunities to improve the
effectiveness and well-being of people at work, and a gifted teacher and storyteller. He is among the
most prolific standard-bearers for people analytics. This new open-source volume is in keeping with
many years of contributions to the practice of understanding people at work.

After nearly 30 years of doing people analytics work and the privilege of leading people analytics teams
at several leading global organizations, I am still excited by the problems we get to solve, the insights we
get to spawn, and the tremendous impact we can have on organizations and the people that comprise
them. This work is human and technical and important and exciting and deeply gratifying. I hope that
you will find this *Handbook of Regression Modeling in People Analytics* helps you uncover new
truths and create positive impacts in your own work.

`r if (knitr::is_html_output()) {"[Alexis A. Fink](https://www.linkedin.com/in/alexisfink/)"} else {"Alexis A. Fink"}` \
December 2020

***Alexis A. Fink, PhD** is a leading figure in people analytics and has led major people analytics teams at Microsoft and Intel before her current role as Vice President of People Analytics and Workforce Strategy at Facebook.  She is a Fellow of the Society for Industrial and Organizational Psychology and is a frequent author, journal editor and research leader in her field.*

